# Comments in GraphQL strings (such as this one) start with the hash (#) symbol.
# This "Book" type defines the queryable fields for every book in our data source.

type Book {
  title: String
}

extend type Query {
  books: [Book]
}
