# Comments in GraphQL strings (such as this one) start with the hash (#) symbol.
# This "Book" type defines the queryable fields for every book in our data source.
type HeatMap {
  viewport_position: String,
  viewport_height:String,
  viewport_width:String,
  url:String,
  title:String,
  url_path:String,
  event_duration:String,
}

extend type Query {
  heatmaps: [HeatMap]
}

extend type Mutation{
  addHeatMap(heatMap:HeatMapParam):Boolean
}
input HeatMapParam {
    viewport_position: String,
    viewport_height:String,
    viewport_width:String,
    url:String,
    title:String,
    url_path:String,
    event_duration:String,
}